# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('url_ref', autoslug.fields.AutoSlugField(editable=False, populate_from=videos.models.url_slugify, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
