# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160420_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 17, 40, 6, 166901, tzinfo=utc)),
        ),
    ]
