# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='partners/')),
            ],
        ),
    ]
