# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
