# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='/media'),
        ),
    ]
