# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20160604_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
