# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20160602_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='partners'),
        ),
    ]
